### ISSUE TITLE
Problems downloading quorum-explorer-webapp image

### ISSUE THREAD

**Issue by oguadilla** [Councilbox/cbx-quorum-explorer#8]
Good evening,

I'm trying to install the explorer in my local server, and when I execute "launch.sh" I get the following error:

Trying to pull repository docker.io/councilbox/quorum-explorer-webapp ...
ERROR: repository docker.io/councilbox/quorum-explorer-webapp not found: does not exist or no pull access

Looking at docker hub, I cannot find that image, same with the other 2

Thanks in advance

**Comment by brunneis** [comment]
Hi @oguadilla, the Docker images weren't uploaded yet to the Docker Hub platform. We are uploading them but in the meanwhile you can build them yourself executing the `build.sh` script.
